#!/usr/bin/env bash
# A script that transfers a file to a server using SCP, accepting 4 parameters:
# 1. The path to the file to be transferred
# 2. The IP of the server
# 3. The username for the SCP connection
# 4. The path to the SSH private key

if [ "$#" -ne 4 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Using scp to transfer the file, disabling strict host key checking
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
