#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting Nginx service if it's not already started
sudo service nginx start

# Allowing Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Update the Nginx configuration to serve the "Hello World" page
sudo sed -i 's|root /var/www/html;|root /var/www/html/;|' /etc/nginx/sites-available/default
sudo sed -i 's|index index.html index.htm index.nginx-debian.html;|index index.nginx-debian.html;|' /etc/nginx/sites-available/default

# Create a simple "Hello World!" index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restarting Nginx without using systemctl
sudo service nginx restart

echo -e "\nCompleted. ✅\n"

