#!/usr/bin/env bash
# Configures an Nginx server to redirect requests from /redirect_me to another page with a 301 Moved Permanently response

# Update the system and install Nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

# Allow Nginx through the firewall
echo -e "\nAllowing Nginx HTTP through the firewall.\n"
sudo ufw allow 'Nginx HTTP'

# Set up the redirect by modifying the Nginx configuration
echo -e "\nSetting up the redirect rule in Nginx.\n"

# Backup the default configuration before modifying it
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bckp

# Use sed to add the redirect block after the server block
sudo sed -i '/server {/a \ \tlocation /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Check if the changes were applied
echo -e "\nModified Nginx configuration:\n"
grep -A 10 "location /redirect_me" /etc/nginx/sites-available/default

# Test Nginx configuration for syntax errors
echo -e "\nTesting Nginx configuration for syntax errors.\n"
sudo nginx -t

# If the configuration is correct, reload Nginx to apply changes
echo -e "\nReloading Nginx to apply changes.\n"
sudo service nginx reload

# Confirm the change was successfully made
echo -e "\nRedirect setup completed. ✅\n"
