#!/usr/bin/env bash
# Configuring web-01 (or web-02) to add HTTP header response

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom HTTP response header to Nginx configuration
sudo sed -i "/server_name _/a add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-enabled/default

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart
