#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 for all IPv4 IPs

# Updating and installing Nginx if not installed
sudo apt update && sudo apt install -y nginx

# Ensuring the default site is enabled
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restarting the Nginx service
sudo service nginx restart
