#!/usr/bin/env bash
# This script enables the default site and restarts Nginx to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo service nginx start
