#!/usr/bin/env bash
# A script that displays "To infinity and beyond" indefinitely and responds to SIGTERM.

# Trap SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop to display the message
while true; do
    echo "To infinity and beyond"
    sleep 2
done
