#!/usr/bin/env bash
# A script that displays the username, user ID, and home directory path for each user in /etc/passwd.

while IFS=: read -r username _ uid _ home_directory _; do
  echo "Username: $username"
  echo "User ID: $uid"
  echo "Home Directory: $home_directory"
  echo ""
done < /etc/passwd
