#!/usr/bin/env bash
# A script that displays "Best School" 10 times, with "Hi" displayed on a new line on the 9th iteration

count=1
while [ "$count" -le 10 ]
do
	if [ "$count" -eq 9 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
