#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes in the format HH:MM

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done
