#!/usr/bin/env bash
# A script that displays the content of the current directory without hidden files,i
# showing only the part of the name after the first dash.

mylist=$(ls)

for i in $mylist; 
do
	echo "$i" | cut -d '-' -f2
done
