#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Backing up /etc/hosts to a temporary file
cp /etc/hosts /tmp/hosts.new

# Modifying localhost and facebook.com entries
echo "127.0.0.2         localhost" > /tmp/hosts.new
echo "8.8.8.8           facebook.com" >> /tmp/hosts.new

# Replacing the /etc/hosts file with the modified one
cp -f /tmp/hosts.new /etc/hosts

# Cleaning up the temporary file
rm /tmp/hosts.new

