#!/usr/bin/env bash

# A script that configures Nginx to run as the nginx user and listen on port 8080

# Change the user Nginx runs as 'nginx'
sed -i 's/user nginx;/user nginx;/' /etc/nginx/nginx.conf

# Configure Nginx to listen on port 8080
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
systemctl restart nginx
