#!/usr/bin/env bash
# A script to configure Nginx to run as the nginx user and listen on port 8080

sed -i 's/user  www-data;/user  nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen  80;/listen  8080;/' /etc/nginx/sites-available/default
systemctl restart nginx
